const data = {
  products: [
    {
      _id: "1",
      name: "Maasai Coloured Crown",
      category: "Crown",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Maasai",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Maasai beads products",
    },
    {
      _id: "2",
      name: "Samburu Bracelet ",
      category: "Bracelets",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Samburu",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Samburu products",
    },
    {
      _id: "3",
      name: "Indegenous Beaded Crown",
      category: "Crown",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Indegenous",
      rating: 4.8,
      numReviews: 10,
      description: "high quality Indegenous beads products",
    },
    {
      _id: "4",
      name: "Maasai Men Necklace",
      category: "Necklace",
      image: "/images/p4.jpg",
      price: 78,
      brand: "Maasai",
      rating: 14,
      numReviews: 10,
      description: "high quality Maasai beads products",
    },
    {
      _id: "5",
      name: "Samburu Wpmen Necklace",
      category: "Necklace",
      image: "/images/p1.jpg",
      price: 65,
      brand: "Samburu",
      rating: 4.5,
      numReviews: 10,
      description: "high quality  beads products",
    },
    {
      _id: "6",
      name: "Indegineous Necklaces ",
      category: "Necklaces",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Indeginous",
      rating: 4.5,
      numReviews: 15,
      description: "high quality products",
    },
  ],
};
export default data;
